sudo: required
language: go
notifications:
  slack:
    rooms:
      - carprk:GwNndSzXdf0hncxr2I5cwwsn#builds
      - carprk:GwNndSzXdf0hncxr2I5cwwsn#login
    on_success: always
    on_cancel: always
    on_failure: always
    on_start: always
    on_error: always
    on_pull_requests: true
go:
  - 1.12.5
env:
  - GO111MODULE=on
install:
  - pip install --user awscli
script:
  - go mod download
  - go build .
after_script:
  - zip $TRAVIS_BUILD_ID.zip $SERVICE_NAME
  - bash .travis-deploy/cloud.sh
